name = "sh0rt-kr"
main = ".output/server/index.mjs"
workers_dev = true
compatibility_date = "2026-09-08"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 * * * *"]

[[routes]]
pattern = "sh0rt.kr"
custom_domain = true
enabled = true
zone_name = "sh0rt.kr"
[[routes]]
custom_domain = true
enabled = true
pattern = "www.sh0rt.kr"
zone_name = "sh0rt.kr"

[assets]
directory = "./.output/public/"
binding = "ASSETS"

[vars]
NUXT_OAUTH_GITHUB_CLIENT_ID = "Ov23liTsdN0bOgaldNIM"
NUXT_OAUTH_GOOGLE_CLIENT_ID = "963112485410-ll8cb0642a68olkr3m3o10nmddq1j4sv.apps.googleusercontent.com"
NUXT_OAUTH_CHZZK_CLIENT_ID = "c084e949-d337-4735-af2b-42db0c68c18d"
NUXT_OAUTH_TWITCH_CLIENT_ID = "j8eszmagvnvbrz92h5w0ix40d4eu8g"
NUXT_PUBLIC_BASE_URL = "https://sh0rt.kr"
NUXT_REPORT_DOMAINS = "sh0rt.kr"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "prod-sh0rt-kr"
database_id = "00601374-c95b-4447-865b-554e20434e5d"
migrations_dir = "server/db/migrations"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "ANALYTICS"

[observability.logs]
enabled = false
invocation_logs = true
